### ISSUE TITLE
Enable https if using cloudflare / provide manual override

### ISSUE THREAD

**Issue by davidcommarmond** [udx/wp-stateless#222]
Hi,
We use cloudflare for the Name Server, and cloudflare serves https content if we use them even if the origin server uses http (See https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-mean- )

Hence, in this scenario, using custom domains and CNAME using cloudflare, it would make sense to allow a manual override enabling https in your plugin settings if the site admin knows what they're doing.

Can you add this in please so chrome can show the website as secure again ?

Thanks.

**Comment by wiiiimm** [comment]
I came here just to file the same request for this feature only to find @davidcommarmond's ;)

**Comment by wiiiimm** [comment]
@davidcommarmond  I have just forked this plugin and added the Force SSL feature.

It is over at -> https://github.com/wpCloud/wp-stateless/pull/282

![screen shot 2018-07-28 at 22 12 46](https://user-images.githubusercontent.com/179761/43357413-9fc72c1e-92b3-11e8-8338-d3ee81e8332b.png)
![screen shot 2018-07-28 at 22 12 15](https://user-images.githubusercontent.com/179761/43357412-98f7347e-92b3-11e8-9d2b-8a9258bb5816.png)

**Comment by roku6185** [comment]
When will this feature be released? Do you have any ETA?

**Comment by davidcommarmond** [comment]
@roku6185 if in the "Domain" field you also add https:// in front of the domain name, it'll serve from https and not http (Not sure where I read this in the code but there's a condition there).

![image](https://user-images.githubusercontent.com/34420248/45211663-ee2add00-b2a3-11e8-91f3-21058697bf6f.png)

Works well on our website https://www.i-spy360-mauritius.com/

**Comment by davidcommarmond** [comment]
@williamli thanks, hopefully it'll be merged to stable, will avoid confusions on how it works.

**Comment by wiiiimm** [comment]
@davidcommarmond @roku6185 it has been merged into stable a while ago in v2.1 https://github.com/wpCloud/wp-stateless/pull/282

**Comment by roku6185** [comment]
I'm using wp-stateless 2.1.7 and I don't see any option for "Force SSL". What version should I be using? I installed Wordpress yesterday, so I guess I'm using the latest version of wp-stateless.

Putting "https://<MY_CDN_DOMAIN>" in the "Custom domain" field doesn't do anything for me. The "Preview" URL doesn't change nor do the image URLs in posts.

**Comment by alimuzzaman** [comment]
Will be release soon.
You can use pre-release version 
https://github.com/wpCloud/wp-stateless/releases/tag/2.1.8-RC1

**Comment by roku6185** [comment]
I dowloaded the pre-release but I can't find the new option "Force SSL" in the code:
`grep "Force SSL" wp-stateless-2.1.8-RC1/ -rn`

, results in nothing. But according to the patch it should be there: https://github.com/wpCloud/wp-stateless/pull/282/files#diff-546de7b1d43b494ce1b2e9bb59e7cdffR185

**Comment by alimuzzaman** [comment]
@roku6185 Sorry for the miscommunication.
Check issue #291 

You just have to prepend  https:// in `Domain` field.
`https://cdn.example.com`

**Comment by roku6185** [comment]
This is very confusing. Prepending "https://" in the Domain field doesn't work. The preview isn't updated and the resulting images (e.g. in posts) only have the raw bucket url. I get the following javascript error on the "Stateless Settings" page:
```
Error: $scope.apply is not a function
angular.min.js:114:210
```

**Comment by alimuzzaman** [comment]
@roku6185 
Please use the this version
https://github.com/wpCloud/wp-stateless/releases/tag/2.1.8-RC2

Some changes was made after RC 1.

**Comment by wiiiimm** [comment]
@alimuzzaman I just tried 2.1.8-RC and experienced the same problem as mentioned by @roku6185. As soon as I added https:// to the domain field, the preview link auto resets itself back to using google storage url.

**Comment by antonkorotkov** [comment]
Closing. This is working in version 2.2.2 https://wordpress.org/plugins/wp-stateless/ Reopen the issues if still have questions.
